baseURL: "http://teodorgenkov.com/"
languageCode: "en-US"
title: "Teodor Genkov"
theme: hugo-profile



Menus:
  main:
    - identifier: about me 
      name: About Me
      title: Informational
      url: /about-me
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects
      weight: 2



hero:
  enable: true
  title: "Teodor Genkov"
  subtitle: "Welcome to my website!"
  content: A passionate Computer Science student. I am on a journey to learn and build different projects to further my programming knowledge.
  #image
  socialLinks:
    fontIcons:
      - icon: fab fa-github
        url: https://github.com/genkovteodor
      # - icon: fab fa-linkedin
      #url: www.linkedin.com/in/genkovteodor
  


# About
about:
  enable: true
  title: "About Me"
  content: |-
    I am Computer Science student. I have a background in IT as a IT Support Technician.

  skills:
    enable: true
    title: "Here are a few technologies I've been working with recently:"
    items:
      - "HTML"
      - "CSS"
      - "Javascript"
      - "Hugo API"
      - "Markdown"

# Experience
experience:
  enable: true
  items:
    - job: "IT Support Technician I"
      company: "UNLV Office of Information Technology"
      companyurl: "unlv.edu"